name: gymai
description: "GymAI â€“ Cross-platform fitness app built with Flutter."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.8.0+1
  equatable: ^2.0.7
  firebase_auth: ^5.5.2
  firebase_core: ^3.13.0
  flutter_dotenv: ^5.2.1
  flutter_riverpod: ^3.0.0
  flutter_secure_storage: ^9.2.4
  freezed_annotation: ^3.0.0
  get_it: ^8.0.3
  go_router: ^14.8.1
  google_sign_in: ^6.2.2
  injectable: ^2.5.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  logger: ^2.5.0
  pretty_dio_logger: ^1.4.0
  riverpod_annotation: ^3.0.0
  shared_preferences: ^2.5.2
  cloud_firestore: ^5.6.12
  animations: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.15
  custom_lint: ^0.8.1
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^6.0.0
  freezed: ^3.0.0
  injectable_generator: ^2.7.0
  json_serializable: ^6.9.4
  mocktail: ^1.0.4
  riverpod_generator: ^3.0.0
  riverpod_lint: ^3.0.0
  very_good_analysis: ^7.0.0
  flutter_native_splash: ^2.4.7

flutter_launcher_icons:
  icon_generator_ignore_pub_warnings: true
  ios: true
  android: true
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/icon/app_icon_android_foreground.png"
  macos:
    generate: true
    image_path: assets/icon/app_icon_black.png
  web:
    generate: true
    image_path: assets/icon/app_icon_black.png
    background_color: "#000000"
    theme_color: "#3B82F6"
  image_path: assets/icon/app_icon_black.png
  min_sdk_android: 21
  remove_alpha_ios: true

flutter_native_splash:
  color: "#000000"
  image: "assets/images/logo_transparent.png"
  android: true
  ios: true
  web: true

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/icons/
    - assets/icon/
